{
 "title": "Общая статистика",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество объявлений",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "book_instance_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество пользователей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество книг",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "books_count", "legendFormat": "__auto" }
   ]
  }
 ]
}